### ISSUE TITLE
So license is free for production?

### ISSUE THREAD

**Issue by NiNJAD3vel0per** [RedisTimeSeries/RedisTimeSeries#101]
I've tried to read license..hard to understand.
What is license model simply for production/commercial? anyone can use it without fee?
Why not just MIT or Apache? Do you guys have a plan to make a commercial license in near future?

**Comment by gkorland** [comment]
You can read more about it here: https://redislabs.com/blog/redis-labs-modules-license-changes/

Basically, as long as you don't develop or use a "Database Product" as defined in the license you're allowed to use the product.

**Comment by NiNJAD3vel0per** [comment]
@gkorland 

Okay, I read the article. 
I am a SaaS developer&provider(opensource/commercial). I am going to use Redis server as one of main databases.
I may include docker compose to let users install Redis freely as desired. Is it okay with RSAL?
The license FAQ clearly indicated that it doesn't allow distribute database(Redis) under RSAL.
So if I include docker image or dockerfile like that, this also means "distributing database"??I  need to know in detail.

**Comment by gkorland** [comment]
>I don't sell Redis itself. I use Redis as a backend database in my product.
>...
>but the main idea is that it is a business application.

That is the main point, as long as you don't sale "Database" but sell another business service it's OK.

**Comment by gkorland** [comment]
If you have any more question feel free to write me - guy dot korland at redislabs dot com

**Comment by sujonvidia** [comment]
Hello, I'm using redis in our messaging / calling application, so far I used it for calling purposes and it's working very good.
Now, I'm implementing redis as a caching layer in front of the cassandra database and need to use the RedisJSON module because nested data structures aren't supported by default. Our service is already in production so I need a confirmation to use the RedisJSON module as application cache layer, we don't develop any database related product, we want to use redis from our node.js application.
So, I think it's okay with RSAL license or correct me if I am wrong here?

**Comment by gkorland** [comment]
If you're not developing a database or a database service and just use it in your node.js application you can use it under the RSAL license.
