### ISSUE TITLE
Breaking change: Minimum CHUNK_SIZE is now 128 bytes

### ISSUE THREAD

**Issue by ppati000** [RedisTimeSeries/RedisTimeSeries#1253]
Hello! As per [this pull request](https://github.com/RedisTimeSeries/RedisTimeSeries/pull/1130), RedisTimeSeries now requires a minimum chunk size of 128 bytes.

Unfortunately, this new requirement is a breaking change for existing code that uses a smaller chunk size (e.g., 64 bytes). Would it be possible to provide some information here?

* Is there any particular reason for enforcing the minimum size of 128 bytes?
* Can we safely keep using existing keys that have a chunk size of 64 bytes, or should we roll over to 128 bytes asap?
* What is the first version of RedisTimeSeries that enforces this requirement?

Thank you for developing and maintaining RedisTimeSeries 🤗

**Comment by LiorKogan** [comment]
This is since 1.6.10 (I just added it to the release notes).

Previous to 1.6.10 we enforced no minimum. Any positive integer was considered valid (though we never tested RTS with very small values), so in 1.6.10 we decided to enforce a minimum, and decided that 128 is a good choice.

64 is still safe, though we won't test future versions with this value.

For any practical use case, any value smaller than 128 would offer no advantage in terms of memory consumptions and ops/sec. (By 'practical use case' I mean few out-of-order insertions).

I believe we can change it back to 64 in future versions (1.8). Please let us know if this is important for you.

**Comment by LiorKogan** [comment]
Update: Minimal `CHUNK_SIZE` value is 48 since 1.8.1
