### ISSUE TITLE
If the label value is encoding it results in Couldn't parse LABELS

### ISSUE THREAD

**Issue by earthgecko** [RedisTimeSeries/RedisTimeSeries#1558]
With redis-stack-server-6.2.6-v7.rhel8.x86_64.tar.gz

```
# Server
redis_version:6.2.12
redis_git_sha1:2d4b9401
redis_build_id:d5c117f9dff7528c
redis_mode:standalone
os:Linux 4.18.0-529.el8.x86_64 x86_64
...
executable:/opt/redis-stack/bin/redis-server
config_file:/etc/redis-stack.conf
```

It appears that if the label value is `"encoding"` then the following error is encountered `TSDB: unknown ENCODING parameter`

For example a very standard Prometheus node_exporter metric that will cause this is:
`promhttp_metric_handler_errors_total{cause="encoding",instance="localhost:9100",job="node_exporter"}`

This seems similar to #1478 which covers commas and parentheses.

I have confirmed that if the label and value are changed to `cause="_encoding"` RedisTimeSeries accepts the metric and creates the TSDB key.

Is this expected and a limitation as per #1478 or is this bug?

**Comment by LiorKogan** [comment]
You are correct.

This is a limitation of the current format.

Instead of  `[LABELS {label value}...]` we should have used `[LABELS count {label value}...]` (where `count` is the number of `label value` pairs) and then you could have used any label, but it is too late to fix this now.

**Comment by LiorKogan** [comment]
Note that if you specify `ENCODING` before `LABELS` you can add a label named `encoding`:

```
redis> TS.CREATE t LABELS encoding x
(error) ERR TSDB: unknown ENCODING parameter
```

but

```
redis> TS.CREATE t ENCODING COMPRESSED LABELS encoding x
OK
```

**Comment by earthgecko** [comment]
Thanks for the workaround @LiorKogan good to know.

And TIL that `COMPRESSED` is the default option if not passed.  Although I probably read that when implementing and perhaps was aware at some point I now realise that there is another mode for me to run in or at least test.  I am not sure if ~90% more memory will be worth with but may be worth a test to find out :)  With a use case of append and read every time series every minute, I would imagine that `UNCOMPRESSED` may be faster in terms of read requests at least.  After I determine what is the easiest way to convert a `COMPRESSED` time series to `UNCOMPRESSED`.  Is there a native method to achieve this, without having to get the time series, delete the time series in Redis and create the time series again as `UNCOMPRESSED` and insert the date again, which would work.

**Comment by LiorKogan** [comment]
There is no way to change an existing time series from `COMPRESSED` to `UNCOMPRESSED` or vice versa. 

For most use cases `COMPRESSED` would be faster than `UNCOMPRESSED`. [We worked together with Intel](https://community.intel.com/t5/Blogs/Tech-Innovation/Cloud/The-Gorilla-in-the-Room-Exploring-RedisTimeSeries-Performance/post/1447569) on optimizing it. An explanation of our compression algorithm is available [here](https://redis.com/blog/redistimeseries-version-1-2-is-here/).

**Comment by earthgecko** [comment]
Once again thanks @LiorKogan, so I do not need to test it :)
I will close this issue as you have more than answered the question.

Just a thought from the Intel blog post. I wonder if a model was ever considered to handle the mantissa and exponent of floating point values as two separate entities?

Like separating out the integer timestamps and the floating points values into two separate memory buffers, but instead
treat the floating points values the same way, separate them into the integers and treat the exponent as an integer as well.
Effectively storing floating point value based time series as 2 time series, although I imagine the would not help with code
complexity or actually optimise the problem.  All magic comes with a prices, often when you gain something in one place you lose can lose it in another.  Theoretically though does it mean that every time series 2 bit compression could be achieved for every data point data, Gorilla achieves 6.01 bits on average for every 64 bit float, could it be achieved with 3 bits or 4 bits as the maximum with the timestamp included?
```
# 3 bit representation of 27.3789
timestamp [integer] |-> mantissa [integer] 27
                    |-> exponent [integer] 3789
# or
timestamp [integer] |-> mantissa [integer] 27, exponent [integer] 3789
# 4 bit representation of 27.3789
timestamp [integer] |-> mantissa [integer] 27
timestamp [integer] |-> exponent [integer] 3789
```
It would be interesting to know if such a method could solve the problem of the 41% of floating point values that cannot be compressed to a single bit.

**Comment by LiorKogan** [comment]
You are correct - there is indeed a place for improvements. Sharing here a different approach we are considering:

Suppose a user calls `TS.ADD key *` value about once  per second with measurements that are received at more-or-less equal intervals from some sensor. Let’s assume that the user don’t need millisecond accuracy. A tenth of a second (or even one second) timestamp accuracy is good enough. Obviously, the double-delta encoding could achieve higher compression rates if the timestamps accuracy would be limited, hence, `*` could be translated to the timestamp of the closest tenth of a second or second. This is not limited only to `*`. The user is very likely to pass timestamps with more accuracy than actually needed.

The same is true for the measurement values: a temperature measurement can, for example, be reported with a 15-digits resolution even though the sensor’s accuracy is only ±0.01. The rest of the digits are simply noise. Obviously, rounding the measurements to the nearest 2^n multiple (e.g., n=-6), such that the sensor’s accuracy is preserved, can lead to a much higher compression rate for the Gorilla compression algorithm. 15-digits resolution is hardly needed in practice.

Remember that double value d=(-1)^s * 2^E * B is stored in 64 bits where S is the sign (1 bit), E is is the exponent (11 bit), and B is the significand (fractional mantissa) (52 bits).


**Suggested new configurable parameters for a time series:**

- Timestamp accuracy: 10^a millisecond - where a, an integer in the range [0 .. 6] specifies the timestamps accuracy. 0 is the default (millisecond accuracy), 3 is one-second accuracy, and 6 is 1000 seconds accuracy (it could be a good choice if samples are reported once per day).

- Sample accuracy: 2^b - where b, as an integer in the range [4 .. 52] specifies the number of meaningful binary digits in the fractional mantissa (the significand) of the floating-point values. 52 is the default (maximal accuracy). 
Suppose that a temperature sensor reports values in the range [±99] degrees and with a 0.1 degree accuracy. 
Practically, we will need to store 999 positive/negative values. Since log2(999) < 10, setting b to 10 will assure us that no meaningful digits are lost.
To make is more user-friendly, users should configure the accuracy in decimal digits - 10^d - where d is an integer in the range [3 .. 16].  
c should be calculated based on d: c = ceil(d * log2(10)) hence:
(d,c): (3, 10) (4, 14) (5, 17) (6, 20) (7, 24) (8, 27) (9, 30) (10, 34) (11, 37) (12, 40) (13, 44) (14, 44) (15, 50)  default: (16, 52)
For the temperature sensor in the example above - [±99] degrees with a 0.1 degree accuracy: d = 3, hence c = 10.

**Comment by earthgecko** [comment]
Providing more configuration options for the parameters for the time series creation does provide solutions, albiet more complex ones for both the user and RedisTimeseries code I imagine.

The degree of precision is always an issue, although users often do not have any control over format or precision of the measures themselves. Unfortunately with RedisTimeseries you have to try and be everything for everyone which is difficult as it has to be able to deal with every type of timestamp and value precision which as you accurately states is "hardly needed in practice", with the rare exceptions.

I imagine that labels and filters have equally hard problems, string representations and computations being arguably more expensive and difficult to optimise than numerical representations.

> It is numerical time series data

People tend to forget that it is strings/names data too and at times the strings side more difficult than the numerical aspect.

Anyway if the model I proposed took into account any timestamp precision representations as well, at best it might achieve constant 4 bit representation and at worst constant 6 bit representation, which is still better than Gorilla's 6.01 bit average, by 0.01 ;)  But I am sure that there better/smarter ways as you point out.

Good luck solving the hard problems, but the team seems to be doing a good enough job at the moment :1st_place_medal:
