### ISSUE TITLE
Bucket aggregation appears not to be rolling over time

### ISSUE THREAD

**Issue by lyrixx** [RedisTimeSeries/RedisTimeSeries#173]
Hello,

I noticed something a bit strange with bucket aggregation.

I have create a small reproducer in PHP. If you are not confortable with this language, I can translate it to another language.
```php// Reset
$redis->del('failed');

// Feed
$startedAtTimestamp = (time() - 25) * 1000; // time() is in second, redis prefer millisecond
$endedAtTimestamp = time() * 1000;
for ($i = $startedAtTimestamp, $j = 0; $i <= $endedAtTimestamp; $i = $i + 100, ++$j) {
    $redis->rawCommand('TS.ADD', 'failed', $i, $j);
}

// Query
$toTimestamp = time() * 1000;
$fromTimestamp = $toTimestamp - 4 * 1000;
$timeBucket = 4 * 1000;

$failedCount = $redis->rawCommand('TS.RANGE', 'failed', $fromTimestamp, $toTimestamp, 'AGGREGATION', 'sum', $timeBucket);
dump($failedCount);
```

So When I Execute it multiple time, It go the following results:

```
array:2 [
  0 => array:2 [
    0 => 1564649976000
    1 => "9180"
  ]
  1 => array:2 [
    0 => 1564649980000
    1 => "250"
  ]
]
```
```
array:2 [
  0 => array:2 [
    0 => 1564649976000
    1 => "6735"
  ]
  1 => array:2 [
    0 => 1564649980000
    1 => "2695"
  ]
]
```
```
array:2 [
  0 => array:2 [
    0 => 1564649976000
    1 => "4390"
  ]
  1 => array:2 [
    0 => 1564649980000
    1 => "5040"
  ]
]
```
```
array:2 [
  0 => array:2 [
    0 => 1564649976000
    1 => "2145"
  ]
  1 => array:2 [
    0 => 1564649980000
    1 => "7285"
  ]
]
```
```
array:2 [
  0 => array:2 [
    0 => 1564649976000
    1 => "2145"
  ]
  1 => array:2 [
    0 => 1564649980000
    1 => "7285"
  ]
]
```
```
array:2 [
  0 => array:2 [
    0 => 1564649980000
    1 => "9180"
  ]
  1 => array:2 [
    0 => 1564649984000
    1 => "250"
  ]
]
```

---

Is this intended ?

**Comment by danni-m** [comment]
@lyrixx in your query you are asking for the last 4 seconds with the aggregation, your start time is changed everytime you run it.
Since we are aggregating by bucketing the time into 4 seconds buckets sometimes the end of your data might fall into 1 or more buckets (the shift depends on the start time).

What are you expecting the output would be?

**Comment by lyrixx** [comment]
As the range is 4 seconds, and the aggregation time is also 4 seconds, I'm expecting to get only one value and not two

**Comment by ashtul** [comment]
@danni-m @gkorland 
Should we keep on any series time of creation and normalize **`(curTime - initTime) % timeBucket`** to it instead of to simple modulus on retention? 
I can see why @lyrixx expect what he expects.

**Comment by danni-m** [comment]
@ashtul it will make the bucketing hard to predict for most use-case, also initTime as a reference can change over time and over different keys. 
To keep all the keys in-sync and have a consistent way of bucketing we will use the time itself for bucketing (graphite and other dbs do the same thing).

**Comment by pvtpogopuschel** [comment]
@ashtul @danni-m Assuming I do not want redis to create buckets by itself but indeed need exactly @lyrixx expected behavior (one value) - is there a way to achieve this without the need for postprocessing in the app? I have tried increasing the time bucket value to extreme amounts, but this does not seem like an elegant solution to me.

Especially queries with AVG do suffer quite a bit if it's not possible to precisely tell where to split those buckets.

**Comment by lyrixx** [comment]
@pvtpogopuschel I don't think so :/ I manually fixed that in my app instead
