### ISSUE TITLE
TS.ADD with * throws error when running in Docker container on Mac OS 

### ISSUE THREAD

**Issue by gkorland** [RedisTimeSeries/RedisTimeSeries#195]
Test
```
while :; do redis-cli TS.ADD temp:raw '*' $RANDOM; done
```
Error
```
(error) TSDB: Timestamp cannot be older than the latest timestamp in the time series
```

```
redis:6379> TS.ADD temp:raw 1565206890585 123
(integer) 1565206890585
redis:6379> TS.ADD temp:raw 1565206890585 123
(integer) 1565206890585
redis:6379> TS.ADD temp:raw 1565206890584 123
(error) TSDB: Timestamp cannot be older than the latest timestamp in the time series
redis:6379>
```

**Comment by ashtul** [comment]
According to [a Docker Engineering post](https://engineering.docker.com/2019/02/addressing-time-drift-in-docker-desktop-for-mac/), since docker is implemented on Mac OS as a VM, its kernel keeps its own clocks which might shift over time. The system then synchronizes the VM with the host which might cause _time travel_ into the past.
No fix is planned for this bug.
