### ISSUE TITLE
Time series denial of service attack on unvalidated or accidental time stamps

### ISSUE THREAD

**Issue by KevinBrogan** [RedisTimeSeries/RedisTimeSeries#303]
If you add a timestamp that is the maximum timestamp value to the key, then no more timestamps will be able to be added to the key. There is no way to delete bad data other than a range lookup and a manual reconstruction of the key with the old data.

RedisTimeSeries workshop.  Type redis-cli to enter the Redis CLI.

redisu$ redis-cli
127.0.0.1:6379> ts.add test 9999999999999999999999 1
(error) TSDB: invalid timestamp
127.0.0.1:6379> ts.add test * 1
(integer) 1578961747531
127.0.0.1:6379> ts.add test * 1
(integer) 1578961749199
127.0.0.1:6379> ts.add test * 1
(integer) 1578961750570
127.0.0.1:6379> ts.add test 1578961750570 1
(integer) 1578961750570
127.0.0.1:6379> ts.add test 1578961750570 1
(integer) 1578961750570
127.0.0.1:6379> ts.add test 1578961750569 1
(error) TSDB: Timestamp cannot be older than the latest timestamp in the time series
127.0.0.1:6379> ts.add test 9578961750570 1
(integer) 9578961750570
127.0.0.1:6379> ts.add test * 1
(error) TSDB: Timestamp cannot be older than the latest timestamp in the time series

**Comment by atwoz** [comment]
I think the design behind RTS and the way the chunk works is what creates that contraint, which I think is ok because I believe it speeds things up and allows for the delta compression which is desired. A possible solution that could even be a configuration is to prevent timestamps with dates in the future to be added which in many uses cases won't ever happen. 

When I say future I don't mean 1 second into the future but for example 1 day into de future. That way if you accidentelly send a timestamp that is 1 year into the future you will just lose that specific day but no the whole year. This parameter could be tuned, so for example you could set to prevent timestamps that are 10 minutes into the future to be inserted. Clocks should not have that much error.

This obviously only prevents accidental denial of service. Someone could just send samples 5 minutes into the future and prevent any samples for 5 minutes but if someone is able to just insert samples into your database as they wish then you have other issues.

**Comment by danni-m** [comment]
This is a known limitation in the way that RedisTimeSeries is implemented. In the future we might consider to have the possibility of changing the history of a timeseries which will make it possible to avoid this problem.

**Comment by wenq1** [comment]
> This is a known limitation in the way that RedisTimeSeries is implemented. In the future we might consider to have the possibility of changing the history of a timeseries which will make it possible to avoid this problem.

This solves (at least partially) #166 #295 #139 

Neither ADD nor INCRBY at the moment allows for modification of history data, which is useful in circumstances when invalid historical values should be revoked

**Comment by danni-m** [comment]
@KevinBrogan @wenq1 we just pushed "out of order" implementation to master, please take it for a spin. There's a big caveat on this feature that it is not time optimized, meaning that when you insert not in order you will occur a time penalty.
Please give it a spin and give us any feedback you have.

**Comment by dwoldo** [comment]
@danni-m  in REF to [this backfill commit](https://github.com/RedisTimeSeries/RedisTimeSeries/commit/6102a1ae6d29eb5ca23900cc88a131e529586a68) when you say "you will occur a time penalty", what is meant by this? How much of an impact?

 Our use-case is that we have distributed APIs and each will receive a large number of timestamped events from 1 or many IoT device. When 100 API endpoints receive many events for a given device (e.g. key) some will take longer to process due to network latency, internal processing latency, etc. When TS.Add is called, they will certainly not be in order but the writes will be within 30 seconds of each other. We cannot guarantee order and are hoping RTS can accommodate this use case for us.

**Comment by danni-m** [comment]
@dwoldo unfortunately your specific use-case will cause higher latency for inserts.
we are working on making this faster using different technique,  but currently we are aiming to allow users to insert "missed" data points.

**Comment by filipecosta90** [comment]
> @danni-m in REF to [this backfill commit](https://github.com/RedisTimeSeries/RedisTimeSeries/commit/6102a1ae6d29eb5ca23900cc88a131e529586a68) when you say "you will occur a time penalty", what is meant by this? How much of an impact?
> 
> Our use-case is that we have distributed APIs and each will receive a large number of timestamped events from 1 or many IoT device. When 100 API endpoints receive many events for a given device (e.g. key) some will take longer to process due to network latency, internal processing latency, etc. When TS.Add is called, they will certainly not be in order but the writes will be within 30 seconds of each other. We cannot guarantee order and are hoping RTS can accommodate this use case for us.

Hi there @dwoldo , as @danni-m stated this was this feature added both to 1.4 and master branches. Regarding overhead of out-of-order insertions it is also related to wether you are using compressed/uncompressed chuncks, how loaded are your instances ( given that for compressed chuncks this requires extra computation ) and the percentage of OOO we're talking about. We will release further documentation on OOO impact on compressed and uncompressed chunks performance, followed by recommendations per use-case.
