### ISSUE TITLE
allow adding with the same timestamp

### ISSUE THREAD

**Issue by krsna-sentieo** [RedisTimeSeries/RedisTimeSeries#366]
I understand its slow to add out of sequence values to the series. But what's issue with having the same timestamp added to the series. we have to store financial data and we have two values for the same timestamp. Is it something that could be added in future?

**Comment by ashtul** [comment]
@krsna-sentieo 
While technically it is not complicated to allow multiple values at one timestamp, we currently believe it is not the right fit. We continuously reconsider as we get feedback from developers.
As a question, would using a higher resolution, eg. microseconds, resolve your issue? or do samples have to be with the same timestamp?

**Comment by wenq1** [comment]
I hesitate to imitate an argument here, so correct me if I'm wrong. However, the same topic happens again and again so I'd like to bring this to the devs' attention.

One of the reasons people start to look into a new project (in this case RedisTimeSeries), despite existing solutions (zset, stream) is it solves a particular problem. In this case same ts, multiple value, arguably a very common use case (why can't two sensors send two sets of data at exactly the same time after all?), as requested in several other issues #166 #295 #333. However, each time a new wheel is invented, there seems to be a "two steps forward, one step back". 

After making sure such issue is not a Fibbonacci request[4], and careful research into the prior art, I think unforutnately I found the answer to be in the "the redis-way" that only the fortunate user base are able to understand[1]. Redis has been famous for inventing new clever structures "i.e. minimalist and computer-science driven, but not imho problem-solving driven. When streams was introduced, the same thing happens. One of the first comments made below the stream announcement is "I think the sorted set would be a much better choice, because then you could still insert items in the past"[3]. Now history has repeated itself.



[1] http://antirez.com/news/129
[2] https://github.com/RedisTimeSeries/RedisTimeSeries/pull/334
[3] https://news.ycombinator.com/item?id=19463306
[4] https://github.com/antirez/redis/issues/116

**Comment by mingrui** [comment]
@ashtul 

Hi, I have a similar use case, example:

stock market trade data have two values: trade:price & trade:amount

Currently my workaround is to use two keys to store these two values separately, with the same timestamp, which feels a bit clunky

would be great if there is an option to enable this feature, in this case I have my own aggregation functions to do computation on (trade:price & trade:amount), and do not necessarily need to have computations done for me by RedisTimeSeries.

Please consider,
Thanks!

**Comment by ashtul** [comment]
@mingrui 
Currently, we do not plan to add the capability of having multiple values in one timestamp. Having this option would make it complex to update one of the values on the timestamp, an option we are developing these days.
Using labels should work great but if you are looking for something else, have you considered using `timestamp` for price and `timestamp+1` for amount?

**Comment by ashtul** [comment]
Hi @mingrui ,
RedisTimeSeries version 1.4 (currently not GA) allows to update the value in a timestamp.
To have multiple values you will need multiple series.
