### ISSUE TITLE
Add command: TS.ALTER

### ISSUE THREAD

**Issue by gkorland** [RedisTimeSeries/RedisTimeSeries#50]
Add support for ALTER command

```
TS.ALTER KEY [RETENTION retentionSecs] [LABELS field value..] 
```

**Comment by chrisa23** [comment]
How would the ALTER function work?

I'm curious for thoughts on allowing the ADD command to also update older points.  An example situation I deal with is weather forecasts, which extend into the future and have many updates to existing points.  Are there concerns with allowing ADD to update older points without error rather than adding a separate ALTER function?   ADD can update the latest point currently.

I also deal with real time data that due to something like a network outage I might miss points and would want to fill in missing values.  I'm guessing this might be problematic with the data chunking.

Perhaps my use cases are outside the general intention of the module, but I figured I'd ask.

**Comment by gkorland** [comment]
The Alter is not going to allow you change historical data but to add/update labels or other settings of the timeseries
