### ISSUE TITLE
Modify `TS.CREATE` to apply default compaction rules similarly to `TS.ADD`

### ISSUE THREAD

**Issue by dpipemazo** [RedisTimeSeries/RedisTimeSeries#887]
After setting a default compaction policy via the `COMPACTION_POLICY` option on module load, it took a bit of debugging to figure out why my keys weren't respecting the policy. It seems the policy is only applied when creating a sample using `TS.ADD` and not applied when calling `TS.CREATE`.

This is indeed [the documented behavior](https://oss.redis.com/redistimeseries/configuration/#compaction_policy-policy), but if it's chosen not to implement this I'd ask to update the docs to be very explicit about not applying the default retention policy on `TS.CREATE` calls.

This behavior is a bit suboptimal for a few reasons:
1. We call `TS.CREATE` explicitly so that we only pass the labels once, at series creation. If we have to rely on the first add implicitly creating the series, we need to modify our code to pass all labels with all adds which results in a lot of unnecessary data transfer to the redis server.
2. We will need to add and then subsequently delete a sample (which I think is now supported), in order to pick up the defaults and have an empty series and maintain the paradigm from (1)

Thanks for taking a look.

**Comment by kramik1** [comment]
I found this out after a bunch of testing as well. This would really simplify the creation of keys for our application. We make sure the keys are created and that there isn't a cross between TS keys and regular key value pair keys before we start the application.

**Comment by LiorKogan** [comment]
@kramik1:

There is a good reason why `COMPACTION_POLICY` only works for `TS.ADD` and not for `TS.CREATE`:

Suppose you define a `COMPACTION_POLICY`, but then, you also want to manually create a compaction rule (using `TS.CREATERULE`). You will first have to create an empty destination key (using `TS.CREATE`) - but now you have a problem, because, due to the `COMPACTION_POLICY` - automatic compaction rules would be created for the destination key.

**Comment by LiorKogan** [comment]
[Documentation updated to describe the motivation](https://redis.io/docs/stack/timeseries/configuration/#compaction_policy).
