### ISSUE TITLE
Timestamp resolution limited to seconds?

### ISSUE THREAD

**Issue by ivost** [RedisTimeSeries/RedisTimeSeries#94]
Default timestamp is in seconds

ts is 64 bits - so it allows millisecond resolution.

What is the behavior of rules and other functions if client inserts time milliseconds insead of seconds

Is it possible to expand time series to use milliseconds?

**Comment by danni-m** [comment]
@ivost there's a documentation gap, you can use milliseconds with the following caveats:
1. On aggregation function you need to pass secs normalized to milisecs (60 -> 60000)
2. `TS.ADD * VALUE` - the automatic timestamp will use secs instead of millisecs. we are planning to fix it.
3. Retention - you need to pass secs normalized to milisecs (60 -> 60000)

**Comment by gkorland** [comment]
https://github.com/RedisTimeSeries/RedisTimeSeries/pull/145
